security:
  encoders:
    App\Entity\User:
      algorithm: auto
  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: email
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    login:
      pattern: ^/api/login
      stateless: true
      guard:
        authenticators:
          - App\Security\LoginAuthenticator
    register:
      pattern: ^/api/register
      stateless: true
      anonymous: lazy
    api:
      pattern: ^/api
      stateless: true
      guard:
        authenticators:
          - App\Security\TokenAuthenticator
    main:
      pattern: ^/
      anonymous: lazy
  #      http_basic: ~

  # activate different ways to authenticate
  # https://symfony.com/doc/current/security.html#firewalls-authentication

  # https://symfony.com/doc/current/security/impersonating_user.html
  # switch_user: true

  access_control:
    - { path: ^/, requires_channel: https }
    - { path: ^/api/admin, roles: ROLE_SUPER_ADMIN }
    # - { path: ^/admin, roles: ROLE_SUPER_ADMIN }
